apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    k8s-app: {{ .Release.Name }}
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace |  default "default" }}
spec:
  progressDeadlineSeconds: 600
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      k8s-app: {{ .Release.Name }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: {{ .Release.Name }}
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-configmap
        - secretRef:
            name: {{ .Release.Name }}-secrets
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        name: {{ .Release.Name }}
        ports:
        - containerPort: {{ .Values.container.containerPort}}
