apiVersion: v1
data:
  DB_USER: cm9vdA==
  DB_PASSWORD: cmVkaGF0MTIzNA==
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace |  default "default" }}
type: Opaque