# Default values for mysqldb.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: mysql
  # Overrides the image tag whose default is the chart appVersion.
  tag: 5.6


service:
  port: 3306
